name: CMake
on:
  push:
  pull_request:
    branches: [ "main" ]
env:
  BUILD_TYPE: RelWithDebInfo
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [ "clang", "gcc", "musl-gcc" ]
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=${{matrix.compiler}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER="clang"
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: CTest
        working-directory: ${{github.workspace}}/build
        run: ctest --output-on-failure
